{
 "title": "Docker",
 "tags": [
  "homelab",
  "docker"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Datasource",
    "query": "victoriametrics-metrics-datasource"
   }
  ]
 },
 "panels": [
  { "title": "Server 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Name",
   "type": "stat",
   "description": "0=cadvisor down, 1=containers running, 2=cadvisor down",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (up{instance=\"10.0.0.X1:8080\"} or on() vector(0))) * 2 + (((count(container_last_seen{instance=\"10.0.0.X1:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}) > bool 0) or on() vector(0)) * (up{instance=\"10.0.0.X1:8080\"} or on() vector(0)))",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"10.0.0.X1:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{instance=\"10.0.0.X1:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Name",
   "type": "stat",
   "description": "0=cadvisor down, 1=containers running, 2=cadvisor down",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (up{instance=\"10.0.0.X1:8080\"} or on() vector(0))) * 2 + (((count(container_last_seen{instance=\"10.0.0.X1:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}) > bool 0) or on() vector(0)) * (up{instance=\"10.0.0.X1:8080\"} or on() vector(0)))",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"10.0.0.X1:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{instance=\"10.0.0.X1:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  { "title": "Server 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Name",
   "type": "stat",
   "description": "0=cadvisor down, 1=containers running, 2=cadvisor down",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (up{instance=\"10.0.0.X2:8080\"} or on() vector(0))) * 2 + (((count(container_last_seen{instance=\"10.0.0.X2:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}) > bool 0) or on() vector(0)) * (up{instance=\"10.0.0.X2:8080\"} or on() vector(0)))",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"10.0.0.X2:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{instance=\"10.0.0.X2:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Name",
   "type": "stat",
   "description": "0=cadvisor down, 1=containers running, 2=cadvisor down",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (up{instance=\"10.0.0.X2:8080\"} or on() vector(0))) * 2 + (((count(container_last_seen{instance=\"10.0.0.X2:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}) > bool 0) or on() vector(0)) * (up{instance=\"10.0.0.X2:8080\"} or on() vector(0)))",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"10.0.0.X2:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{instance=\"10.0.0.X2:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  { "title": "Server 3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Name",
   "type": "stat",
   "description": "0=cadvisor down, 1=containers running, 2=cadvisor down",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (up{instance=\"10.0.0.X3:8080\"} or on() vector(0))) * 2 + (((count(container_last_seen{instance=\"10.0.0.X3:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}) > bool 0) or on() vector(0)) * (up{instance=\"10.0.0.X3:8080\"} or on() vector(0)))",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"10.0.0.X3:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{instance=\"10.0.0.X3:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Name",
   "type": "stat",
   "description": "0=cadvisor down, 1=containers running, 2=cadvisor down",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (up{instance=\"10.0.0.X3:8080\"} or on() vector(0))) * 2 + (((count(container_last_seen{instance=\"10.0.0.X3:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}) > bool 0) or on() vector(0)) * (up{instance=\"10.0.0.X3:8080\"} or on() vector(0)))",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"10.0.0.X3:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{instance=\"10.0.0.X3:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  { "title": "HA / Grafana Local", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Name",
   "type": "stat",
   "description": "0=cadvisor down, 1=containers running, 2=cadvisor down",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (up{instance=\"ha-host.local:8080\"} or on() vector(0))) * 2 + (((count(container_last_seen{instance=\"ha-host.local:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}) > bool 0) or on() vector(0)) * (up{instance=\"ha-host.local:8080\"} or on() vector(0)))",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"ha-host.local:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{instance=\"ha-host.local:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Name",
   "type": "stat",
   "description": "0=cadvisor down, 1=containers running, 2=cadvisor down",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (up{instance=\"ha-host.local:8080\"} or on() vector(0))) * 2 + (((count(container_last_seen{instance=\"ha-host.local:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}) > bool 0) or on() vector(0)) * (up{instance=\"ha-host.local:8080\"} or on() vector(0)))",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"ha-host.local:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{instance=\"ha-host.local:8080\",id=~\"/system.slice/docker-.*\\\\.scope\"})",
     "legendFormat": "RAM"
    }
   ]
  }
 ]
}