version: '3.8'

services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter_omv
    restart: unless-stopped
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - /:/host:ro,rslave
    command:
      - --path.rootfs=/host

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest  # ARM64 OK
    container_name: cadvisor_omv
    restart: unless-stopped
    network_mode: host
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro